//Hanna WHat is time complexity?Why do we need to analze it???

//Time complexity is basically all about scalabity. How long does it take your code to run when the input gets larger? It is determined by the number of basic operations( addition, subtraction, multiplication, division, for loops, 
)

//Asymptotic Analysis means we evaluate the performance of an algorithm in terms of input size (we don’t measure the actual running time). We calculate, how does the time (or space) taken by an algorithm increases with the input size.We don't consider actual time or the machine speed. 

// the machine dependent constants can always be ignored after certain values of input size.

//Big O is the worst case analysis of code. 

//O of theta is the average or closest to true analysis. Usually confused with Big O in interviews

//O of Omega is the best case analysis. This is useless as the worst case can run for years. 

//The main idea of asymptotic analysis is to have a measure of efficiency of algorithms that doesn’t depend on machine specific constants, and doesn’t require algorithms to be implemented and time taken by programs to be compared.